### ISSUE TITLE
review FTDI chip USB signals

### ISSUE THREAD

**Issue by sbourdeauducq** [sinara-hw/sinara#255]
The Sayma card seems unusually picky about what USB cables it will accept, and which ones will cause the device not to be detected or get detected and then disconnected immediately.

**Comment by jbqubit** [comment]
Has this been explored further? @sbourdeauducq What did you see that suggests this is a cable issue and not something else? With a single USB cable I sometimes see strange behavior #872 and sometimes not.

**Comment by gkasprow** [comment]
@sbourdeauducq if you observe MMC reset which causes full power cycle, this is probably caused by embedded MMC FLASH programmer. You can disable this feature by removing a jumper that connects Source of the T23 is missing GND. So I placed a piece of wire that connects pin 2 of T24 with pin 2 of T24.  But still, the capacitance between D and G of T23 may cause resets, so it's better to lift pin 3 of T23 and isolate it.

**Comment by jbqubit** [comment]
> So I placed a piece of wire that connects pin 2 of T24 with pin 2 of T24. 

Is that a typo?

**Comment by gkasprow** [comment]
edit: T23 with T24 :)

**Comment by gkasprow** [comment]
Here is drawing which will help
![obraz](https://user-images.githubusercontent.com/4325054/34018743-acf8bed2-e12b-11e7-842d-d83d306ec3bc.png)

**Comment by hartytp** [comment]
No action points here. This doesn't add anything to the other issues discussing USB JTAG.
