### ISSUE TITLE
Sayma RTM schematics cosmetics

### ISSUE THREAD

**Issue by hartytp** [sinara-hw/sinara#410]
Very low priority issue, but at some point it would be nice to have a cleaner version of the Sayma RTM schematics:

- [ ] Lots of text is overlapping and hard to read
- [x] Huge annotation saying "FIducials missing" on first page
- [ ] Lots of the annotations are in a large font size and run over components.
- [x] Once we DNP the ADCs, can they be removed from the schematic PDF posted to the release (removes a few pages and makes it easier to read).

**Comment by marmeladapk** [comment]
- [ ] On RTM_IPMI sheet there's overlapping text on I2C port
- [ ] Si5324 sheet cdr_clk_clean3, rst  port has overlapping text, 
- [ ] date out of bounds on most sheets
- [ ] Sheet numbering is weird
- [ ] "Matching between (...)" text goes beyond sheet

Otherwise all other text is readable and not obstructed by anything.

**Comment by hartytp** [comment]
I think this is no longer relevant now we've moved to AD, so closing
