### ISSUE TITLE
Sayma: SC1 skew with 2X interpolation

### ISSUE THREAD

**Issue by jbqubit** [sinara-hw/sinara#559]
Follow-on to #558. Scope and 100 MHz clock to Sayma are phase locked. Here, frequency0 is 210 MHz. 

## zero-skew check
First, check for skew between channels on single DAC. No skew as expected. 

![tek006_001](https://user-images.githubusercontent.com/20543958/41207219-cb9bb296-6cdf-11e8-8967-8f3b63054445.png)

## SC1 check 
Compare phase between a pair of channels spanning both DACs on single Sayma. 1/(2400 MHz) is 416 ps. 1/(210 MHz) is 4.76 ns. 

![tek006_005](https://user-images.githubusercontent.com/20543958/41207226-e19d82f4-6cdf-11e8-8437-39d23dbb49e3.png)
![tek006_006](https://user-images.githubusercontent.com/20543958/41207227-e1a63fc0-6cdf-11e8-93e6-f8efa28e65fc.png)

Jitter is higher than expected but no large phase jumps on the scope. It looks like the jitter  is due to a time-varying ripple on the sinusoids.

**Comment by hartytp** [comment]
@jbqubit it's not totally clear to me what the "issue" is here, versus you using the issue tracker as a place to dump your notes. Can you make this clearer in future?

> Compare phase between a pair of channels spanning both DACs on single Sayma. 1/(2400 MHz) is 416 ps. 1/(210 MHz) is 4.76 ns.

Where is 2.4GHz coming from? I thought you only changed the HMC7043 settings, which would give a 1.2GHz DAC clock. Or, did you also increase the HMC830 output frequency?

> Jitter is higher than expected but no large phase jumps on the scope. It looks like the jitter is due to a time-varying ripple on the sinusoids.

Is this the issue?

If so, can you post a spectrum? It's not clear to me that this is anything other than image frequencies, since you don't have a reconstruction filter afaict. A spectrum would make that clearer.
