### ISSUE TITLE
[sayma_rtm] IC48 LTM4619 VOUT1/2 of 6V is above abs max rating of 5V

### ISSUE THREAD

**Issue by jordens** [sinara-hw/sinara#565]
Don't know whether it's a problem right now, but it's probably not best practice.
Credits to Sven Rotter for noticing.

**Comment by gkasprow** [comment]
good catch, we cannot leave it as it is. We can replace it with i.e. [TPSM84824](http://www.ti.com/product/TPSM84824)

**Comment by hartytp** [comment]
@gkasprow is this likely to cause problems during testing?

**Comment by gkasprow** [comment]
I didn't notice any issues with this converter.
I'm quite surprised why is there such limitation. It's not voltage breakdown of MOSFETs, since they operate at 12V anyway. Could be internal capacitor voltage rating.
I wouldn't expect problems with such operating condition, but we will change the module to make sure we operate within recommended limits.

**Comment by gkasprow** [comment]
We will use [TPSM84824MOLR](https://pl.mouser.com/ProductDetail/Texas-Instruments/TPSM84824MOLR?qs=W0yvOO0ixfEo%2FgpT5Em6eQ%3D%3D)
it is much smaller and cheaper than LTM4619

**Comment by gkasprow** [comment]
done

**Comment by marmeladapk** [comment]
Shouldn't TT resistor be around 70kOhm? After using equation from datasheet with approximated values resistor should be much larger than it is now.

**Comment by gkasprow** [comment]
Good catch. Replaced with 30k according to table 8 in Datasheet.
![obraz](https://user-images.githubusercontent.com/4325054/53811291-4db72c00-3f59-11e9-837a-40e683d05845.png)
