### ISSUE TITLE
Swap DACB _P with _N (or change in AFE)

### ISSUE THREAD

**Issue by marmeladapk** [sinara-hw/sinara#581]
In ADC_DAC_AFE_Mezzanine.

It leads to 180 deg phase difference on channels next to each other.

ed: Also check polarity on all channels. If I plug every other channel then signals from DAC1 have 180 deg phase difference to signals from DAC0.

**Comment by marmeladapk** [comment]
@gkasprow Should this be implemented on AFE or on RTM?

**Comment by gkasprow** [comment]
I wouldn't change AFE since it already exists.

**Comment by dhslichter** [comment]
@gkasprow aren't we going to redo the connectors for AFE mezzanine and make new ones without power detectors, etc?  This seems to me like an important bug to fix on the RTM itself, because it would be very subtle and potentially frustrating for people who are trying to make in-phase signals (granted I know that people will be calibrating out cable lengths too, so it's not the end of the world).

**Comment by gkasprow** [comment]
I mean that I don't want to change existing FMC-like TestMod .

**Comment by marmeladapk** [comment]
This is fixed. I checked chain from DAC to output stage on AFE and lines are not swapped.
