### ISSUE TITLE
Sayma with VHDCI, 1.5 V led not illuminated

### ISSUE THREAD

**Issue by jbqubit** [sinara-hw/sinara#587]
M-Labs added support for VHDCI control of EEMs. https://github.com/m-labs/artiq/issues/817#issuecomment-406186764

Start with an AMC+RTM system that works on benchtop. Add FMC DIO 32 ch adapter and observe that 1.5 V LED on Sayma AMC doesn't illuminate and current drawn from 12 V is 0.5 A and sometimes 1.5 A. Nothing is printed on the console. 

Not sure if this is related but Pin 18 on FMC DIO 32 ch adapter is shorted to ground by Creotech as shipped. This modification was made on all four of the adapter boards at UMD.

**Comment by sbourdeauducq** [comment]
I have not seen this issue on the board I tested (and I was surprised that something like that did not happen, considering Sayma's track record).
I also have the rework on the FMC card.
Try a different Sayma board?

**Comment by gkasprow** [comment]
IS the 3.3V on? I observed such issue in the past but it was resolved by changing power rail sequencing. 1.5V must wakeup first, than 3.3V. Otherwise FMC board supplies the FPGA via protection diodes and for some yet not identified reason, 1.5V rail gets power which confuses the Exar chip which disables this rail.
It seems that changing the power sequencing did not resolve the problem entirely.
I'll revert the original power sequencing and try to recreate the issue on my board.
It's quite possible that some FMC-DIO boards have different number of input channels enabled than another ones which results in random behaviour.

**Comment by gkasprow** [comment]
I cannot find in my lab any FMC DIO to recreate the problem. Will ask Creotech if they have spare one.

**Comment by jbqubit** [comment]
@gkasprow Were you able to locate a FMC DIO?

**Comment by gkasprow** [comment]
@jbqubit Yes, guys from Creotech have 2 pcs. I will get the boards tomorrow.

**Comment by gkasprow** [comment]
@jbqubit  OK, I have the FMC board and I managed to recreate the issue

**Comment by jbqubit** [comment]
@gkasprow Thanks for the heads up. Looking forward to getting this fixed.

**Comment by gkasprow** [comment]
@jbqubit I found what was the issue.
The power sequencing was set 1.1V - 3.3V - 1.8V - 1.5V.
The FMC LVDS board has [FIN1101](http://www.mouser.com/ds/2/149/FIN1101-53552.pdf) buffers.
They have undocumented feature - with floating inputs, the output common mode is 2.6V instead of 1.1...1.3V. The current is roughly 3mA So when you plug only FMC board, without input connected, all buffers drive their outputs with 2.6V causing parasitic supply of the FPGA rail.
And because the AMC 3.3V power was enabled first, it supplied 1.8V rail with 2V by protection diodes activating Exar protection and power on sequence stopped. 1.8V LED was on, but 1.5V rail was off.
I modified power on sequence so now we have 1.5 - 1.8 -3.3V and it works fine.
I solved this issue some time ago but for some reason this change was not recorded in files.

**Comment by gkasprow** [comment]
@wizath please embed the hex file below and publish binary for MMC.
[Sayma_AMC_2.zip](https://github.com/sinara-hw/sinara/files/2464359/Sayma_AMC_2.zip)

@jbqubit please update MMC and don't forget to command the MMC to flash Exar chip.

**Comment by wizath** [comment]
[update_new_xr.zip](https://github.com/sinara-hw/sinara/files/2465077/update_new_xr.zip)
H - for AMC, J - for rtm

**Comment by hartytp** [comment]
@gkasprow I'm closing this as I think it's now resolved. AFAICT no hw changes are needed, just tweaks to the MMC firmware. Please reopen if any hardware changes are required here
